# config.yaml
api:
  key: "YOUR API KEY"

paths:
  excel_file: "keywords.xlsx"
  output_folder: "output"
  generated_problems_folder: "output/generated_problems"
  validation_results_folder: "output/validation_results"
  word_output_folder: "output/word_documents"

excel_settings:
  start_row: 2
  column_range:
    - "C"
    - "D"
    - "E"
  filename_cell: "C1"  # 파일명을 가져올 셀 위치

output_settings:
  filename_prefix: ""  # 파일명 앞에 붙일 텍스트 (필요한 경우)
  filename_suffix: ""  # 파일명 뒤에 붙일 텍스트 (필요한 경우)
  json_extension: ".json"
  word_extension: ".docx"
  validation_extension: "_validation.json"

word_settings:
  margins:
    top: 1.5    # in centimeters
    bottom: 1.5
    left: 1.5
    right: 1.5
  fonts:
    passage:
      name: "함초롱바탕"
      size: 9
      line_spacing: 14.4  # 160% of 9pt
    question:
      name: "맑은 고딕"
      size: 9
      line_spacing: 11.7  # 130% of 9pt
      character_spacing: -0.9  # -10% spacing
    option:
      name: "함초롱바탕"
      size: 9
      line_spacing: 14.4
    answer:
      name: "맑은 고딕"
      size: 9
      line_spacing: 11.7

gpt_settings:
  problem_generation:
    model: "gpt-4o"
    temperature: 0.3
    max_tokens: 2500
    top_p: 0.9
    frequency_penalty: 0.15
    presence_penalty: 0.15
    system_prompt: |
      너는 유능한 고등학교 영어 시험 문제 제작자야. 
      문제가 매우 정교하고 이의제기를 할 수 없을정도로 매우 잘 만든 문제들을 제작하는 사람으로서 
      깊이 고민해서 문제들을 만들어.

  validation:
    model: "gpt-4o"
    temperature: 0.3
    max_tokens: 1500
    top_p: 0.9
    frequency_penalty: 0.1
    presence_penalty: 0.1

prompts:
  problem_generation: |
    다음 지문으로 정교한 문제들을 만들어.
    문제의 난이도는 고등학생 최고 최상위 난이도로 매우 어렵게 지문속 단어의 어려운 유의어와 
    반의어들을 적극 사용해서 만들어줘.
    문제 유형은 다음 유형들에서 골라서 만들어. 글의 주제찾기, 지문 속 표현의 의미 혹은 함축적 의미로 올바른 것은(이 유형의 문제는 지문 속 표현을 문제 부분에 명시해야해), 지문을 올바르게 이해한 사람의 발언 찾기, 등 다양한 문제 유형.   
    한 지문당 2문제 만들어.
    문제의 질문은 한글로 묻고 선지 즉, 선택지는 무조건 영어로 하고 총 5개의 선지로 하고 1~5번을 부여해.
    마크다운 같은건 절대 쓰지마.
    또한 큰 따옴표를 연속해서 사용하지마.
    그냥 웬만해선 (따올표)를 쓰지마.
    그리고 문제 번호 앞에 '문제' 라고 붙이지마.
    또한 문제 번호끝에 : 말고 . 을 붙여.
    지문:{본문}

  answer_validation: |
    다음 문제와 선지를 분석하여 정답이 명확한지, 복수 정답은 없는지 확인해.
    지문: {본문}
    문제: {문제}
    선지:
    {선지}
    현재 정답: {정답}

    다음 사항들을 중점적으로 확인해주세요:
    1. 정답이 명확하고 하나만 존재하는가?
    2. 선지들이 서로 충분히 구별되는가?
    3. 오답이 명백한 오답인가?
    4. 문제가 지문의 내용을 정확히 반영하는가?

  english_correction: |
    다음 문제의 선지 중 영어가 아닌 부분이 있어. 내용적 누락 없이 영어로 수정해.
    지문: {본문}
    문제: {문제}
    현재 선지:
    {선지}
    수정이 필요한 선지 번호: {indices}

    다음 기준을 따라 수정해주세요:
    1. 완벽한 영어 문장으로 수정
    2. 원래 의미를 최대한 보존
    3. 문법적으로 정확한 표현 사용
    4. 고등학교 수준에 맞는 어휘 사용

output_format:
  json_template: |
    {
      "문제번호": "",
      "본문": "",
      "문제들": [
        {
          "문제번호": "",
          "문제": "",
          "선지": [],
          "정답": ""
        }
      ]
    }
