gpt_settings:
  problem_generation:
    model: "gpt-4o"
    temperature: 0.3
    max_tokens: 2500
    top_p: 0.9
    frequency_penalty: 0.15
    presence_penalty: 0.15
    system_prompt: |
      너는 유능한 고등학교 영어 시험 문제 제작자야. 
      문제가 매우 정교하고 이의제기를 할 수 없을정도로 매우 잘 만든 문제들을 제작하는 사람으로서 
      깊이 고민해서 문제들을 만들어.
prompts:
  problem_generation: |
    다음 지문으로 정교한 문제들을 만들어.
    문제의 난이도는 고등학생 최고 최상위 난이도로 매우 어렵게 지문속 단어의 어려운 유의어와 
    반의어들을 적극 사용해서 만들어줘.
    문제 유형은 다음 유형들에서 골라서 만들어. 글의 주제찾기, 지문 속 표현의 의미 혹은 함축적 의미로 올바른 것은(이 유형의 문제는 지문 속 표현을 문제 부분에 명시해야해), 지문을 올바르게 이해한 사람의 발언 찾기, 등 다양한 문제 유형.   
    한 지문당 2문제 만들어.
    문제의 질문은 한글로 묻고 선지 즉, 선택지는 무조건 영어로 하고 총 5개의 선지로 하고 1~5번을 부여해.
    마크다운 같은건 절대 쓰지마.
    또한 큰 따옴표를 연속해서 사용하지마.
    그냥 웬만해선 (따올표)를 쓰지마.
    그리고 문제 번호 앞에 '문제' 라고 붙이지마.
    또한 문제 번호끝에 : 말고 . 을 붙여.
    지문:{본문}

output_format:
  json_template: |
    {
      "문제번호": "",
      "본문": "",
      "문제들": [
        {
          "문제번호": "",
          "문제": "",
          "선지": [],
          "정답": ""
        }
      ]
    }